#!/bin/bash
protected_branches=( "master" "develop" "mapper-support" "branch_for_debugging_this_script" )
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for protected_branch in "${protected_branches[@]}"
do
    :
    if [ $protected_branch = $current_branch ]  
    then  
        read -p "You're about to push $protected_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
        echo
        if echo $REPLY | grep -E '^[Yy]$' > /dev/null
        then
            : # do nothing
        else
            exit 1 # push will not execute
        fi
    fi  

done
read -p "Did you run tests? [y|n] " -n 1 -r < /dev/tty
echo
if echo $REPLY | grep -E '^[Yy]$' > /dev/null
then
    exit 0 # push will execute
fi
exit 1 # push will not execute
